# -*- coding: utf-8 -*-
"""HR ANALYSIS .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wrlmn7bmOpuXCPH5jZDOxyHHtSjOCcKD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (classification_report, confusion_matrix,
                             roc_auc_score, roc_curve, ConfusionMatrixDisplay)
from sklearn.pipeline import Pipeline
from sklearn.inspection import permutation_importance

DARK_BG   = "#1C1C2E"
CARD_BG   = "#252542"
BLUE      = "#4F8EF7"
PINK      = "#E05C97"
TEAL      = "#2EC4B6"
GOLD      = "#FFD166"
TEXT      = "#E0E0E0"
GRID      = "#3A3A5C"

plt.rcParams.update({
    'figure.facecolor': DARK_BG,
    'axes.facecolor': CARD_BG,
    'axes.edgecolor': GRID,
    'axes.labelcolor': TEXT,
    'xtick.color': TEXT,
    'ytick.color': TEXT,
    'text.color':       TEXT,
    'grid.color':       GRID,
    'grid.linestyle':   '--',
    'grid.alpha':       0.4,
    'font.family':      'DejaVu Sans',
})

print("=" * 60)
print("HR ANALYTICS - FULL PIPLINE")
print("=" * 60)

df = pd.read_csv(r"C:\Users\SAURABH SAHU\Desktop\HR\HR_Analytics_Clean.csv")
print(f"\n Loaded dataset: {df.shape[0]} rows * {df.shape[1]} columns")

#DROP CONSTANT / REDUNDANT COLUMNS
drop_cols = ["EmployeeCount", "Over18", "StandardHours", "EmployeeNumber",]
df.drop(columns=drop_cols, inplace=True)
print(f" Dropped {len(drop_cols)} constant columns")

#MISSING VALUE CHECK
missing = df.isnull().sum()
print(f" Missing values: {missing.sum()} (dataset is clean)")

#DATA TYPE AUDIT
cat_cols = df.select_dtypes('object').columns.tolist()
num_cols = df.select_dtypes('number').columns.tolist()
print(f" Categorical columns: {len(cat_cols)}")
print(f" Numerical columns: {len(num_cols)}")

#MAP ORDINAL LABLES FOR READABILITY
sat_map = {1: 'Low', 2: 'Medium', 3: 'High', 4: 'Very High'}
wlb_map = {1: 'Bad', 2: 'Good', 3: 'Better', 4: 'Best'}
edu_map = {1: 'Below College', 2: 'College', 3: 'Bachelor', 4: 'Master', 5: 'Doctor'}
perf_map = {1: 'Low', 2: 'Good', 3: 'Excellent', 4:'Outstanding'}

df['JobSatisfaction'] = df['JobSatisfaction'].map(sat_map)
df['EnvironmentSatisfaction_Label'] = df['EnvironmentSatisfaction'].map(sat_map)
df['WorkLifeBalance_Label'] = df["WorkLifeBalance"].map(wlb_map)
df['Education_Label'] = df['Education'].map(edu_map)
df["PerformanceRating_Label"] = df["PerformanceRating"].map(perf_map)

#Feature Engineering
df['AttritionBinary']    = (df['Attrition'] == 'Yes').astype(int)
df['IncomePerYearExp']   = (df['MonthlyIncome'] / (df['TotalWorkingYears'] + 1)).round(2)
df['OverTimeFlag']       = (df['OverTime'] == 'Yes').astype(int)
df['TenureGroup']        = pd.cut(df['YearsAtCompany'],
                                   bins=[-1, 1, 3, 7, 15, 100],
                                   labels=['0–1 yr','2–3 yr','4–7 yr','8–15 yr','15+ yr'])
df['AgeGroup']           = pd.cut(df['Age'],
                                   bins=[17, 25, 35, 45, 60],
                                   labels=['18–25','26–35','36–45','46–60'])
df['IncomeGroup']        = pd.cut(df['MonthlyIncome'],
                                   bins=[0, 3000, 6000, 10000, 25000],
                                   labels=['Low','Medium','High','Very High'])

print("\n✔  Feature engineering complete — 6 new features added")
print(f"\n{'─'*60}")
print(f"  Overall Attrition Rate : {df['AttritionBinary'].mean():.1%}")
print(f"  Total Employees        : {len(df)}")
print(f"  Employees Left (Yes)   : {df['AttritionBinary'].sum()}")
print(f"  Employees Retained (No): {(df['AttritionBinary']==0).sum()}")
print(f"{'─'*60}")

#EDA
print("\n[EDA] Generating visualisations...\n")

#plot 1 Attrition Overview

fig, axes = plt.subplots(1, 4, figsize=(18, 4))
fig.patch.set_facecolor(DARK_BG)
fig.suptitle("HR Analytics — Attrition Overview", fontsize=18,
             fontweight='bold', color=TEXT, y=1.02)

kpis = [
    ("Total Employees", f"{len(df):,}", BLUE),
    ("Attrition Rate",  f"{df['AttritionBinary'].mean():.1%}", PINK),
    ("Avg Monthly Income", f"${df['MonthlyIncome'].mean():,.0f}", TEAL),
    ("Avg Tenure",      f"{df['YearsAtCompany'].mean():.1f} yrs", GOLD),
]
for ax, (label, value, color) in zip(axes, kpis):
    ax.set_facecolor(CARD_BG)
    ax.text(0.5, 0.62, value, ha='center', va='center',
            fontsize=32, fontweight='bold', color=color, transform=ax.transAxes)
    ax.text(0.5, 0.28, label, ha='center', va='center',
            fontsize=11, color=TEXT, transform=ax.transAxes)
    for spine in ax.spines.values():
        spine.set_edgecolor(color)
        spine.set_linewidth(2)
    ax.set_xticks([]); ax.set_yticks([])

plt.tight_layout()
plt.savefig('/content/plot1_kpi_banner.png', dpi=150, bbox_inches='tight',
            facecolor=DARK_BG)
plt.close()
print("  ✔  Plot 1: KPI Banner")

#2 Attrition by deparment and job role
fig, axes = plt.subplots(1,2, figsize=(16,6))
fig.patch.set_facecolor(DARK_BG)

#2 Attrition by deparment and job role
fig, axes = plt.subplots(1,2, figsize=(16,6))
fig.patch.set_facecolor(DARK_BG)
dept_attr = df.groupby('Department')['AttritionBinary'].mean().sort_values(ascending=True)
colors_dept = [PINK if v == dept_attr.max() else BLUE for v in dept_attr.values]
bars = axes[0].barh(dept_attr.index, dept_attr.values * 100, color=colors_dept,
                     edgecolor='none', height=0.55)
axes[0].set_xlabel('Attrition Rate (%)', color=TEXT)
axes[0].set_title('Attrition Rate by Department', color=TEXT, fontweight='bold', pad=12)
axes[0].axvline(df['AttritionBinary'].mean() * 100, color=GOLD,
                linestyle='--', linewidth=1.5, label='Overall Avg')
axes[0].legend(facecolor=CARD_BG, edgecolor=GRID, labelcolor=TEXT)
axes[0].grid(axis='x')
for bar, val in zip(bars, dept_attr.values):
    axes[0].text(val * 100 + 0.3, bar.get_y() + bar.get_height()/2,
                 f'{val:.1%}', va='center', color=TEXT, fontsize=10)

# Job role attrition
role_attr = df.groupby('JobRole')['AttritionBinary'].mean().sort_values(ascending=True)
colors_role = [PINK if v >= 0.20 else BLUE for v in role_attr.values]
axes[1].barh(role_attr.index, role_attr.values * 100, color=colors_role,
             edgecolor='none', height=0.55)
axes[1].set_xlabel('Attrition Rate (%)', color=TEXT)
axes[1].set_title('Attrition Rate by Job Role', color=TEXT, fontweight='bold', pad=12)
axes[1].axvline(df['AttritionBinary'].mean() * 100, color=GOLD,
                linestyle='--', linewidth=1.5)
axes[1].grid(axis='x')

high_patch = mpatches.Patch(color=PINK, label='High Risk (≥20%)')
norm_patch = mpatches.Patch(color=BLUE, label='Normal Risk')
axes[1].legend(handles=[high_patch, norm_patch], facecolor=CARD_BG,
               edgecolor=GRID, labelcolor=TEXT)

plt.tight_layout()
plt.savefig('/content/plot2_dept_role.png', dpi=150, bbox_inches='tight',
            facecolor=DARK_BG)
plt.close()
print("  ✔  Plot 2: Department & Job Role Attrition")

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.patch.set_facecolor(DARK_BG)
fig.suptitle("Key Attrition Drivers", fontsize=16,
             fontweight='bold', color=TEXT, y=1.01)

def plot_cat_attrition(ax, col, title, colors=None):
    grp = df.groupby(col)['AttritionBinary'].mean().sort_values(ascending=False)
    if colors is None:
        colors = [PINK if v == grp.max() else BLUE for v in grp.values]
    bars = ax.bar(grp.index, grp.values * 100, color=colors,
                  edgecolor='none', width=0.6)
    ax.set_title(title, color=TEXT, fontweight='bold', pad=10)
    ax.set_ylabel('Attrition Rate (%)', color=TEXT)
    ax.axhline(df['AttritionBinary'].mean() * 100, color=GOLD,
               linestyle='--', linewidth=1.5, alpha=0.8)
    ax.grid(axis='y')
    for bar, val in zip(bars, grp.values):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.4,
                f'{val:.0%}', ha='center', va='bottom', color=TEXT, fontsize=9)
    ax.set_xticklabels(grp.index, rotation=20, ha='right', fontsize=9)

plot_cat_attrition(axes[0][0], 'OverTime',       'Overtime vs Attrition')
plot_cat_attrition(axes[0][1], 'MaritalStatus',   'Marital Status vs Attrition')
plot_cat_attrition(axes[0][2], 'BusinessTravel',  'Business Travel vs Attrition')
plot_cat_attrition(axes[1][0], 'JobSatisfaction', 'JobSatisfaction vs Attrition',
                   colors=[PINK, PINK, BLUE, BLUE])
plot_cat_attrition(axes[1][1], 'WorkLifeBalance_Label', 'Work-Life Balance vs Attrition')
plot_cat_attrition(axes[1][2], 'TenureGroup',     'Tenure Group vs Attrition')

plt.tight_layout()
plt.savefig('/content/plot3_drivers.png', dpi=150, bbox_inches='tight',
            facecolor=DARK_BG)
plt.close()
print("  ✔  Plot 3: Key Attrition Drivers")

#INCOME DISRITBUTION
fig, axes = plt.subplots(1, 2, figsize=(16, 6))
fig.patch.set_facecolor(DARK_BG)

# KDE by attrition
for label, color in [('No', BLUE), ('Yes', PINK)]:
    subset = df[df['Attrition'] == label]['MonthlyIncome']
    axes[0].hist(subset, bins=40, color=color, alpha=0.65,
                 label=f'Attrition: {label}', edgecolor='none', density=True)
axes[0].set_title('Monthly Income Distribution by Attrition', color=TEXT,
                   fontweight='bold')
axes[0].set_xlabel('Monthly Income ($)', color=TEXT)
axes[0].set_ylabel('Density', color=TEXT)
axes[0].legend(facecolor=CARD_BG, edgecolor=GRID, labelcolor=TEXT)
axes[0].grid(axis='y')

# Income by Department + Job Level
dept_jl = df.groupby(['Department', 'JobLevel'])['MonthlyIncome'].mean().unstack()
dept_jl.plot(kind='bar', ax=axes[1], colormap='cool', edgecolor='none', width=0.7)
axes[1].set_title('Avg Income by Department & Job Level', color=TEXT,
                   fontweight='bold')
axes[1].set_xlabel('Department', color=TEXT)
axes[1].set_ylabel('Avg Monthly Income ($)', color=TEXT)
axes[1].set_xticklabels(axes[1].get_xticklabels(), rotation=15, ha='right')
axes[1].legend(title='Job Level', facecolor=CARD_BG,
               edgecolor=GRID, labelcolor=TEXT, title_fontsize=9)
axes[1].grid(axis='y')

plt.tight_layout()
plt.savefig('/content/plot4_income.png', dpi=150, bbox_inches='tight',
            facecolor=DARK_BG)
plt.close()
print("  ✔  Plot 4: Income Analysis")

fig, ax = plt.subplots(figsize=(14, 10))
fig.patch.set_facecolor(DARK_BG)

num_features = ['Age', 'MonthlyIncome', 'YearsAtCompany', 'YearsInCurrentRole',
                'TotalWorkingYears', 'JobSatisfaction', 'EnvironmentSatisfaction',
                'WorkLifeBalance', 'JobInvolvement', 'PercentSalaryHike',
                'TrainingTimesLastYear', 'DistanceFromHome', 'AttritionBinary',
                'OverTimeFlag', 'JobLevel', 'StockOptionLevel']

corr = df[num_features].corr()
mask = np.triu(np.ones_like(corr, dtype=bool))

cmap = sns.diverging_palette(220, 20, as_cmap=True)
sns.heatmap(corr, mask=mask, cmap=cmap, center=0, annot=True,
            fmt='.2f', annot_kws={'size': 8}, linewidths=0.5,
            linecolor=DARK_BG, ax=ax, vmin=-1, vmax=1)
ax.set_title('Feature Correlation Matrix', color=TEXT, fontweight='bold',
             fontsize=14, pad=15)
ax.set_facecolor(CARD_BG)

plt.tight_layout()
plt.savefig('/content/plot5_correlation.png', dpi=150, bbox_inches='tight',
            facecolor=DARK_BG)
plt.close()
print("  ✔  Plot 5: Correlation Heatmap")

print(df[num_features].dtypes)

df['JobSatisfaction'] = df['JobSatisfaction'].map({
    'Low': 1,
    'Medium': 2,
    'High': 3,
    'Very High': 4
})

corr = df[num_features].corr()

print(df[num_features].dtypes)

print("\n" + "═"*60)
print("  KEY EDA INSIGHTS")
print("═"*60)

ot_yes = df[df['OverTime']=='Yes']['AttritionBinary'].mean()
ot_no  = df[df['OverTime']=='No']['AttritionBinary'].mean()
print(f"\n  1. OVERTIME: Employees with overtime have {ot_yes:.1%} attrition")
print(f"     vs {ot_no:.1%} for those without — {ot_yes/ot_no:.1f}× higher risk")

single = df[df['MaritalStatus']=='Single']['AttritionBinary'].mean()
married = df[df['MaritalStatus']=='Married']['AttritionBinary'].mean()
print(f"\n  2. MARITAL STATUS: Single employees attrit at {single:.1%}")
print(f"     vs Married at {married:.1%}")

low_sat = df[df['JobSatisfaction']<=2]['AttritionBinary'].mean()
high_sat = df[df['JobSatisfaction']>=3]['AttritionBinary'].mean()
print(f"\n  3. JOB SATISFACTION: Low satisfaction → {low_sat:.1%} attrition")
print(f"     High satisfaction → {high_sat:.1%} attrition")

early = df[df['TenureGroup']=='0–1 yr']['AttritionBinary'].mean()
veteran = df[df['TenureGroup']=='15+ yr']['AttritionBinary'].mean()
print(f"\n  4. TENURE: First-year employees attrit at {early:.1%}")
print(f"     vs only {veteran:.1%} for 15+ year veterans")

low_inc = df[df['MonthlyIncome'] < 3000]['AttritionBinary'].mean()
high_inc = df[df['MonthlyIncome'] >= 10000]['AttritionBinary'].mean()
print(f"\n  5. INCOME: Low-income band (<$3K) attrition: {low_inc:.1%}")
print(f"     High-income (>$10K) attrition: {high_inc:.1%}")

#MACHINE LEARNING MODEL
print("\n" + "═"*60)
print("  MACHINE LEARNING — ATTRITION PREDICTION")
print("═"*60)

#encode features
df_ml = df.copy()

# Drop label columns we added (keep original ordinals)
drop_label = ['JobSatisfaction', 'EnvironmentSatisfaction_Label',
              'WorkLifeBalance_Label', 'Education_Label', 'PerformanceRating_Label',
              'TenureGroup', 'AgeGroup', 'IncomeGroup', 'Attrition', 'IncomePerYearExp']
df_ml.drop(columns=drop_label, inplace=True)

le = LabelEncoder()
for col in df_ml.select_dtypes('object').columns:
    df_ml[col] = le.fit_transform(df_ml[col])

X = df_ml.drop('AttritionBinary', axis=1)
y = df_ml['AttritionBinary']

print(f"\n  Features: {X.shape[1]}  |  Target: AttritionBinary")
print(f"  Class balance — No: {(y==0).sum()} | Yes: {(y==1).sum()}")

#Train / Test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

#train random forest
rf = RandomForestClassifier(
    n_estimators=200, max_depth=8, min_samples_leaf=5,
    class_weight='balanced', random_state=42, n_jobs=-1)
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)
y_prob = rf.predict_proba(X_test)[:, 1]

# Cross-validation
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(rf, X, y, cv=cv, scoring='roc_auc')

print(f"\n  ── Random Forest Results ──")
print(f"  ROC-AUC (Test)   : {roc_auc_score(y_test, y_prob):.3f}")
print(f"  ROC-AUC (CV Mean): {cv_scores.mean():.3f} ± {cv_scores.std():.3f}")
print(f"\n  Classification Report:")
print(classification_report(y_test, y_pred, target_names=['Retained','Attrited']))

#model performace dashabpoard
fig, axes = plt.subplots(1, 3, figsize=(18, 6))
fig.patch.set_facecolor(DARK_BG)
fig.suptitle("Random Forest — Model Performance", fontsize=16,
             fontweight='bold', color=TEXT, y=1.02)

# ROC Curve
fpr, tpr, _ = roc_curve(y_test, y_prob)
auc_val = roc_auc_score(y_test, y_prob)
axes[0].plot(fpr, tpr, color=BLUE, lw=2.5, label=f'RF (AUC = {auc_val:.3f})')
axes[0].plot([0,1],[0,1], color=GRID, lw=1.5, linestyle='--', label='Random')
axes[0].fill_between(fpr, tpr, alpha=0.15, color=BLUE)
axes[0].set_xlabel('False Positive Rate', color=TEXT)
axes[0].set_ylabel('True Positive Rate', color=TEXT)
axes[0].set_title('ROC Curve', color=TEXT, fontweight='bold')
axes[0].legend(facecolor=CARD_BG, edgecolor=GRID, labelcolor=TEXT)
axes[0].grid()

# condfuis matrx
cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(cm, display_labels=['Retained', 'Attrited'])
disp.plot(ax=axes[1], cmap='Blues', colorbar=False)
axes[1].set_title('Confusion Matrix', color=TEXT, fontweight='bold')
axes[1].set_facecolor(CARD_BG)

# Feature Importance (Top 15)
importances = pd.Series(rf.feature_importances_, index=X.columns)
top15 = importances.nlargest(15).sort_values()
colors_fi = [PINK if v >= top15.quantile(0.75) else BLUE for v in top15.values]
axes[2].barh(top15.index, top15.values, color=colors_fi, edgecolor='none', height=0.65)
axes[2].set_title('Top 15 Feature Importances', color=TEXT, fontweight='bold')
axes[2].set_xlabel('Importance Score', color=TEXT)
axes[2].grid(axis='x')

plt.tight_layout()
plt.savefig('/content/plot6_model_perf.png', dpi=150, bbox_inches='tight',
            facecolor=DARK_BG)
plt.close()
print("\n  ✔  Plot 6: Model Performance")

#risk score on full dataset
df['AttritionRiskScore'] = rf.predict_proba(
    df_ml.drop('AttritionBinary', axis=1))[:, 1].round(3)
df['RiskTier'] = pd.cut(df['AttritionRiskScore'],
                         bins=[0, 0.25, 0.50, 1.0],
                         labels=['Low Risk', 'Medium Risk', 'High Risk'])

risk_summary = df.groupby('RiskTier').agg(
    Count=('AttritionBinary','count'),
    ActualAttrition=('AttritionBinary','sum'),
    AvgIncome=('MonthlyIncome','mean'),
    AvgTenure=('YearsAtCompany','mean')
).round(1)
print("\n  Risk Tier Summary:")
print(risk_summary.to_string())

high_risk_overtime = df[(df['RiskTier']=='High Risk') & (df['OverTime']=='Yes')]['AttritionBinary'].mean()
print(f"\n  High-Risk + Overtime attrition rate: {high_risk_overtime:.1%}")

#work force peroformance analysis
print("\n" + "═"*60)
print("  WORKFORCE PERFORMANCE ANALYSIS")
print("═"*60)

# ── PLOT 7: Performance & Salary Hike ─────────────────────
fig, axes = plt.subplots(1, 3, figsize=(18, 6))
fig.patch.set_facecolor(DARK_BG)
fig.suptitle("Workforce Performance Insights", fontsize=16,
             fontweight='bold', color=TEXT, y=1.02)

# Training vs Performance
train_perf = df.groupby('TrainingTimesLastYear')['PerformanceRating'].mean()
axes[0].plot(train_perf.index, train_perf.values, color=TEAL,
             marker='o', linewidth=2.5, markersize=8)
axes[0].fill_between(train_perf.index, train_perf.values,
                      alpha=0.2, color=TEAL)
axes[0].set_title('Training Sessions vs Performance', color=TEXT, fontweight='bold')
axes[0].set_xlabel('Training Times Last Year', color=TEXT)
axes[0].set_ylabel('Avg Performance Rating', color=TEXT)
axes[0].grid()

# Salary hike by performance
perf_hike = df.groupby('PerformanceRating_Label')['PercentSalaryHike'].mean()
axes[1].bar(perf_hike.index, perf_hike.values, color=[BLUE, GOLD],
            edgecolor='none', width=0.5)
axes[1].set_title('Avg Salary Hike by Performance', color=TEXT, fontweight='bold')
axes[1].set_xlabel('Performance Rating', color=TEXT)
axes[1].set_ylabel('Avg Salary Hike (%)', color=TEXT)
axes[1].grid(axis='y')
for i, (idx, val) in enumerate(perf_hike.items()):
    axes[1].text(i, val + 0.15, f'{val:.1f}%', ha='center',
                 color=TEXT, fontsize=11, fontweight='bold')

# Job Involvement vs Attrition
involvement_attr = df.groupby('JobInvolvement')['AttritionBinary'].mean()
labels = ['Low', 'Medium', 'High', 'Very High'][:len(involvement_attr)]
axes[2].bar(labels, involvement_attr.values * 100,
            color=[PINK, PINK, BLUE, BLUE][:len(labels)],
            edgecolor='none', width=0.5)
axes[2].set_title('Job Involvement vs Attrition', color=TEXT, fontweight='bold')
axes[2].set_xlabel('Job Involvement Level', color=TEXT)
axes[2].set_ylabel('Attrition Rate (%)', color=TEXT)
axes[2].axhline(df['AttritionBinary'].mean()*100, color=GOLD,
                linestyle='--', linewidth=1.5, label='Overall Avg')
axes[2].legend(facecolor=CARD_BG, edgecolor=GRID, labelcolor=TEXT)
axes[2].grid(axis='y')

plt.tight_layout()
plt.savefig('/content/plot7_performance.png', dpi=150, bbox_inches='tight',
            facecolor=DARK_BG)
plt.close()
print("  ✔  Plot 7: Workforce Performance")

import os

path = os.path.join(os.getcwd(), 'HR_Analytics_Clean.csv')
df_export.to_csv(path, index=False)

print("Saved at:", path)

export_cols = [
    'Age', 'AgeGroup', 'Gender', 'MaritalStatus', 'Education', 'Education_Label',
    'EducationField', 'Department', 'JobRole', 'JobLevel', 'BusinessTravel',
    'OverTime', 'DistanceFromHome', 'MonthlyIncome', 'IncomeGroup',
    'PercentSalaryHike', 'StockOptionLevel', 'TrainingTimesLastYear',
    'YearsAtCompany', 'TenureGroup', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
    'TotalWorkingYears', 'NumCompaniesWorked',
    'JobSatisfaction', 'JobSatisfaction',
    'EnvironmentSatisfaction', 'EnvironmentSatisfaction_Label',
    'WorkLifeBalance', 'WorkLifeBalance_Label',
    'JobInvolvement', 'RelationshipSatisfaction',
    'PerformanceRating', 'PerformanceRating_Label',
    'Attrition', 'AttritionBinary',
    'AttritionRiskScore', 'RiskTier', 'OverTimeFlag'
]

df_export = df[export_cols].copy()
df_export.to_csv('HR_Analytics_Clean.csv', index=False)

print("\n  ✔  Clean dataset exported (HR_Analytics_Clean.csv)")
print(f"     Shape: {df_export.shape}")
print("\n" + "═"*60)
print("  ALL DONE — 7 Plots + Clean Dataset Ready")
print("═"*60)

